pysite:
    base:
        url: http://yourdomain.com
        basedir: /path/to/pysite
        module: website
        templatedir: ./templates
    database:
        uri: mysql://user:password@mysqlhost/dbname?charset=utf8
